# Generated by Django 3.0.3 on 2020-08-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200808_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_periods',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='activity_periods',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
    ]
