# Generated by Django 3.0.3 on 2020-08-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200808_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_periods',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app.Members'),
        ),
    ]
